services:
  - type: web
    name: cafesafepro
    runtime: node
    plan: free
    buildCommand: rm -rf node_modules .next && npm ci && npx prisma generate && npx prisma db push --skip-generate && NODE_OPTIONS='--max-old-space-size=4096' next build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cafesafepro-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://cafesafepro.onrender.com
      - key: NODE_VERSION
        value: 18.17.0

databases:
  - name: cafesafepro-db
    plan: free
